"use client";

import React from 'react';
import { GenerateIntelligentSalarySlipLayoutOutput, GenerateIntelligentSalarySlipLayoutInput } from '@/ai/flows/generate-intelligent-salary-slip-layout';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { cn } from '@/lib/utils';

interface SlipRendererProps {
  layout: GenerateIntelligentSalarySlipLayoutOutput;
  data: GenerateIntelligentSalarySlipLayoutInput;
}

export default function SlipRenderer({ layout, data }: SlipRendererProps) {
  const formatValue = (value: any, type: 'text' | 'amount' | 'date') => {
    if (value === null || value === undefined) return "";
    if (type === 'amount') {
      return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(Number(value));
    }
    if (type === 'date') {
      return new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    }
    return String(value);
  };

  return (
    <div className="bg-white p-8 md:p-12 min-h-[800px] flex flex-col print-container">
      {layout.sections.map((section, sIdx) => (
        <div key={sIdx} className={cn("mb-8", section.layoutHint === "two columns" ? "grid grid-cols-2 gap-8" : "flex flex-col gap-4")}>
          {section.title && (
            <h3 className="text-lg font-bold border-b-2 border-primary/20 pb-2 mb-2 text-primary uppercase tracking-wider no-print-background">
              {section.title}
            </h3>
          )}
          
          <div className={cn(
            "w-full",
            section.layoutHint === "inline" ? "flex flex-wrap gap-x-12 gap-y-4" : "space-y-4"
          )}>
            {section.elements.map((element, eIdx) => {
              if ("type" in element && element.type === "image") {
                const imgData = data[element.key as keyof GenerateIntelligentSalarySlipLayoutInput];
                if (!imgData) return null;
                return (
                  <div key={eIdx} className={cn("flex flex-col", element.positionHint === "bottom-right" ? "items-end" : "")}>
                    {element.label && <span className="text-xs text-muted-foreground mb-1">{element.label}</span>}
                    <img src={imgData as string} alt={element.label || "Image"} className="max-h-24 object-contain" />
                  </div>
                );
              }

              if ("type" in element && element.type === "salaryBreakdownTable") {
                return (
                  <div key={eIdx} className="w-full mt-4">
                    {element.title && <h4 className="font-semibold mb-2">{element.title}</h4>}
                    <Table className="border rounded-lg overflow-hidden">
                      <TableHeader className="bg-muted/30">
                        <TableRow>
                          {element.headers.map((h, i) => (
                            <TableHead key={i} className={cn("font-bold text-foreground", i === 1 ? "text-right" : "")}>{h}</TableHead>
                          ))}
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {data.salaryBreakdown.map((item, i) => (
                          <TableRow key={i}>
                            <TableCell>{item.item}</TableCell>
                            <TableCell className="text-right font-mono">{formatValue(item.amount, 'amount')}</TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                );
              }

              if ("type" in element && (element.type === 'text' || element.type === 'amount' || element.type === 'date')) {
                const value = data[element.key as keyof GenerateIntelligentSalarySlipLayoutInput];
                return (
                  <div key={eIdx} className={cn(
                    "flex flex-col",
                    element.alignment === 'center' ? 'items-center text-center' :
                    element.alignment === 'right' ? 'items-end text-right' : 'items-start'
                  )}>
                    <span className="text-xs text-muted-foreground uppercase tracking-tight">{element.label}</span>
                    <span className={cn(
                      "text-base text-foreground",
                      element.emphasize ? "font-bold text-xl" : "font-medium"
                    )}>
                      {formatValue(value, element.type)}
                    </span>
                  </div>
                );
              }

              return null;
            })}
          </div>
        </div>
      ))}

      <div className="mt-auto pt-12 text-center text-[10px] text-muted-foreground italic">
        Generated by DrivePay • Computer Generated Salary Slip • No physical signature required unless specified.
      </div>
    </div>
  );
}